### PR TITLE
Big rework

### PR DESCRIPTION
**Pull request by iDroid27210**

### CODE REVIEW

**Comment by iDroid27210** [comment]
And you could also ESLint your work... that's not professionnal at all Kyle !

**Comment by ArtutoGamer** [comment]
But what if I forgot my ID

**Comment by iDroid27210** [comment]
idk
kyle a solution ?

**Comment by GRIMMYY** [comment]
does it solve all my problems for me?

**Comment by ArtutoGamer** [comment]
Just paste ur token here so ur god kyle can fix it up

**Comment by Kyle2000** [comment]
k

**Comment by sh98** [comment]
o

**Pull request closed without merging**
